Wa 3
AgustinCanteros/grupo-n-2 pull request #10
Opened 2022-11-04 14:02 UTC by jarriech

## Jira Ticket

[wa-3]

## Description 
add create-role to migrations file create-role

## Evidence:
(Put screenshots/video/gifs here)

2022-11-04 14:26 UTC, germanWalton requested changes

2022-11-04 14:26 UTC, germanWalton commented on database/migrations/20221102-create-role.js
> +        type: Sequelize.STRING
Add allowNull: false to the field name

2022-11-04 20:37 UTC, ledelaespriella approved these changes
all approved

2022-11-05 01:00 UTC, germanWalton approved these changes

2022-11-05 01:01 UTC, merged