[DB]: model creation and user migration
AgustinCanteros/grupo-n-2 pull request #2
Opened 2022-11-03 03:24 UTC by HugoCavalero92

## Jira Ticket WA-1

- [WA-1]

## Description
Model creation and user migration
AS: Administrator
I Want: To have control
To: Of users

## Evidence:
![DBUser](https://user-images.githubusercontent.com/72712498/199641886-20a7c275-4bbc-4841-a977-44985697d44b.PNG)

2022-11-03 12:14 UTC, germanWalton approved these changes

2022-11-03 13:56 UTC, ledelaespriella requested changes
Please correct migrations

2022-11-03 13:56 UTC, ledelaespriella commented on database/migrations/20221102141110-create-user.js
> +        type: Sequelize.INTEGER
### Pending

add the foreign key in the migration:

` roleId: {
        type: Sequelize.INTEGER,
references: {
          model: {
            tableName: 'Role',
            schema: 'schema'
          },
          key: 'id'
        },
        allowNull: false
},`

2022-11-03 19:40 UTC, ledelaespriella requested changes
Please correct migrations

2022-11-03 19:40 UTC, ledelaespriella commented on database/migrations/20221102141110-create-user.js
> +        references: { model: { tableName: 'Role', schema: 'schema' }, key: 'id' },
### Pendingn

Code correct:

`roleId: { 
        type: Sequelize.INTEGER, 
        references: { 
          model: 'Roles' , 
          key: 'id' 
        },
        allowNull: false 
      },`

View in mysql Workbench:

![Captura de Pantalla 2022-11-03 a la(s) 2 39 37 p m](https://user-images.githubusercontent.com/84211273/199818284-d8743b36-3624-4f16-a3be-c0714bddb9ef.png)

2022-11-04 00:36 UTC, ledelaespriella approved these changes
### **passed**

2022-11-04 00:37 UTC, merged