[SWAGGER IMPLEMENTATION - WA-39]
AgustinCanteros/grupo-n-2 pull request #51
Opened 2022-11-10 04:21 UTC by germanWalton

## Jira Ticket

- [WA-39](https://n2-alkemy-sku-31-10.atlassian.net/browse/WA-39?atlOrigin=eyJpIjoiMjY2ODE0MTU1ZTQzNGMzN2JiNjUzOTllOGM3OGVmMjYiLCJwIjoiaiJ9)

## Description
AS: Dev
I Want: to implement the swagger ui configuration
To: test the endpoints

## Evidence:

![swagger](https://user-images.githubusercontent.com/71266221/200999820-41ad7187-87be-4d7c-981e-3dc97d581373.jpg)

2022-11-10 23:30 UTC, ledelaespriella requested changes

2022-11-10 23:30 UTC, ledelaespriella commented on middlewares/token/jwt.middleware.js
> +      res.status(401).send(err);
delete this file and leave the other

2022-11-11 13:25 UTC, ledelaespriella approved these changes

2022-11-11 14:13 UTC, HugoCavalero92 approved these changes

2022-11-11 14:13 UTC, merged