[SWAGGER] categories docs
AgustinCanteros/grupo-n-2 pull request #55
Opened 2022-11-11 10:09 UTC by ganozikovsky

## Jira Ticket

- [WA-42](https://n2-alkemy-sku-31-10.atlassian.net/jira/software/projects/WA/boards/1?selectedIssue=WA-42)

## Description
AS: member of project
I Want: see how to use endpoints of categories
To: correctly apply each of the endpoints

## Evidence:

![1](https://user-images.githubusercontent.com/103380329/201317500-5e75a2e9-20ab-48a3-ba23-c82dfacb9880.png)

## POST
![POST CATEGORIES](https://user-images.githubusercontent.com/103380329/201317534-6eab5dac-a7ed-4538-90cf-026e21a77b28.png)

## GET
![GET CATEGORIES](https://user-images.githubusercontent.com/103380329/201317564-7ff570e5-acde-4391-9a68-2be45f905b67.png)

## GET BY ID
![GET CATEGORY BY ID](https://user-images.githubusercontent.com/103380329/201317580-b1f3dd24-5bd8-44cd-841e-232ab81f5c9f.png)

## UPDATE BY ID
![UPDATE CATEGORY BY ID](https://user-images.githubusercontent.com/103380329/201317606-b23556d7-1b8b-4be9-be80-b98c0f449d57.png)

## DELETE BY ID
![DELETE CATEGORY BY ID](https://user-images.githubusercontent.com/103380329/201317640-392d030e-7efd-4812-b490-c7fe1cd6d4da.png)

2022-11-11 16:05 UTC, ledelaespriella approved these changes
correct conflicts

2022-11-11 17:19 UTC, ledelaespriella requested changes
add examples in the documentation

2022-11-12 20:14 UTC, ledelaespriella approved these changes

2022-11-12 20:16 UTC, germanWalton approved these changes

2022-11-12 20:17 UTC, merged