[ENDPOINT]: Created endpoint to make transactions.
AgustinCanteros/grupo-n-2 pull request #7
Opened 2022-11-03 22:18 UTC by marce-alf

## Jira Ticket

- [WA-19]

## Description
Created endpoint and middleware to validate and create transactions.

AS: a user
I Want: the ability to do transactions
To: make movements.

## Evidence:
![create-transaction](https://user-images.githubusercontent.com/112339651/199844653-979b5796-ab34-45f0-a339-b0469b03dbba.png)

2022-11-04 00:59 UTC, ledelaespriella commented on controllers/transaction.js
> +        `[Error retrieving index] - [index - GET]: ${error.message}`
correct error description.

> [Error retrieving Transaction] - [Transaction - POST]:

2022-11-04 01:20 UTC, ledelaespriella requested changes
## Pending

Attach evidence of how the return would be when a parameter is passed that does not meet the conditions or is missing

2022-11-04 01:20 UTC, ledelaespriella commented on routes/transaction.js
> +router.post('/', validator(postTransactionSchema), postCreateTransaction);
You must create a folder called transactions and inside place the js of the route.

![Captura de Pantalla 2022-11-03 a la(s) 8 04 19 p m](https://user-images.githubusercontent.com/84211273/199863122-b0f818f1-525c-4a5d-afd2-483ac2c507e5.png)

2022-11-04 01:20 UTC, ledelaespriella commented on routes/index.js
> +router.use('/transactions', transactionRoutes);
Delete line 8

2022-11-04 18:14 UTC, ledelaespriella requested changes
### **Pending**

change file names

2022-11-04 18:14 UTC, ledelaespriella commented on routes/transaction.js
> +module.exports = router;
rename file to: transactions.routes.js

2022-11-04 18:14 UTC, ledelaespriella commented on controllers/transaction.js
> +module.exports = {
rename file to: transactions.controller.js

2022-11-04 20:05 UTC, ledelaespriella approved these changes
All approved

2022-11-05 01:12 UTC, germanWalton approved these changes

2022-11-05 01:12 UTC, merged